// lib/utils/webAppManifest.ts
import { Platform } from 'react-native';

/** Makes the website installable as an app (Add to Home Screen) - which is also
 * what lets an iPhone receive push notifications at all. Added to the page at
 * runtime, because the page shell is generated by Expo; the browser reads these
 * tags when someone installs, so adding them after load is enough. */
export function installWebAppManifest(): void {
  if (Platform.OS !== 'web' || typeof document === 'undefined') return;

  const add = (tag: 'link' | 'meta', attributes: Record<string, string>, matchKey: string) => {
    if (document.head.querySelector(`${tag}[${matchKey}="${attributes[matchKey]}"]`)) return;
    const element = document.createElement(tag);
    for (const [name, value] of Object.entries(attributes)) element.setAttribute(name, value);
    document.head.appendChild(element);
  };

  add('link', { rel: 'manifest', href: '/manifest.webmanifest' }, 'rel');
  add('link', { rel: 'apple-touch-icon', href: '/icons/apple-touch-icon.png' }, 'rel');
  add('meta', { name: 'theme-color', content: '#2563EB' }, 'name');
  add('meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }, 'name');
  add('meta', { name: 'apple-mobile-web-app-title', content: 'Jageer' }, 'name');
}
